trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    echo "<html><body>Hello</body></html>" > index.html
    echo "<footer><p style='position:fixed; bottom:0; right:0;'>$(date)</p></footer>" >> index.html
  displayName: 'HTML f치jl gener치l치sa d치tummal'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: 'index.html'
    artifactName: 'html-artifact'