trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@1
  inputs:
    versionSpec: '3.x'
    addToPath: true

- script: |
    echo "<html><body>Hello</body></html>" > index.html
    echo "<footer><p style='position:fixed; bottom:0; right:0;'>$(date)</p></footer>" >> index.html
  displayName: 'HTML fájlom'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: 'index.html'
    artifactName: 'html-artifact'